# GET all transactions
# GET http://127.0.0.1:5000/transactions/getall

# POST a new transaction
# POST http://127.0.0.1:5000/transactions/add HTTP/1.1
# content-type: application/json

# {
#     "merchant": "test payroll",
#     "transaction_type": "income",
#     "amount": 152.83,
#     "transaction_date": "2022-07-30"
# }

# DELETE a transaction
# POST http://127.0.0.1:5000/transactions/delete HTTP/1.1
# content-type: application/json

# {
#     "id": 3
# }